# Generated by Django 5.1.2 on 2024-11-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='profession',
            new_name='machine_model',
        ),
    ]
